server {
    listen 80;
    
    # 1. Sirve los archivos de React (Frontend)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. Proxy inverso hacia el Backend de Ventas
    location /api/v1/ventas {
        proxy_pass http://api-ventas:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 3. Proxy inverso hacia el Backend de Despachos
    location /api/v1/despachos {
        proxy_pass http://api-despachos:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}